# Manually triggered workflow
name: Trigger Recipe Search

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      input_recipe:
        description: 'Recipe to find:'
        # Default value if no value is explicitly provided
        default: 'pizza'
        # Input has to be provided for the workflow to run
        required: true

jobs:
    find_recipe:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Find recipe from foodie.fi
          run: |
            docker run \
              -v ${PWD}/reports:/opt/robotframework/reports:Z \
              -v ${PWD}/tasks:/opt/robotframework/tests:Z \
              -v ${PWD}/reports/file://opt/robotframework/temp/reports/file/ \
              -e ROBOT_OPTIONS="--variable RECIPE_TO_SEARCH:${{ github.event.inputs.recipe }}" \
              --user $(id -u):$(id -g) \
              ppodgorsek/robot-framework:latest
        - name: print results
          run: ls # todo: print file where number is 
        - name: Upload run results
          uses: actions/upload-artifact@v1
          if: always()
          with:
            name: reports
            path: ${{ github.workspace }}/reports
